// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pidqmmrdcgwdyvrugjbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZHFtbXJkY2d3ZHl2cnVnamJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTgwNzAsImV4cCI6MjA2Njg5NDA3MH0.eUviZ24Y5Zq9Falj76y7RbFSKN8kE0cqCf6KUV-OYBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});